### ISSUE TITLE
Actividad-2-infografia-Sandrasalgadoperez-1BS

### ISSUE THREAD

**Issue by Sandrasalgado** [SistemasTecTlaxiaco/actividad-2-infografia-Sandrasalgado#1]
[actividad2-infografia-sandrasalgadoperez-1BS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-infografia-Sandrasalgado/files/9474626/actividad2-infografia-sandrasalgadoperez-1BS.pdf)

**Comment by Daisy-GonzalezLita12** [comment]
18.2

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
